# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full
# model_name_or_path: mistralai/Mistral-7B-v0.1

# Data training arguments
dataset_mixer:
  #HuggingFaceH4/ultrafeedback_binarized: 1.0
  UCLA-AGI/SPIN_iter0: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# Trainer arguments
bf16: true
beta: 0.1
alpha: 0.0
# isNewSPIN: true
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
hub_model_id: zephyr-7b-spin
# hub_model_id: mistral-7b-spin
# learning_rate: 5.0e-7
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 2
optim: rmsprop
output_dir: outputs/zephyr-7b-spin/
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: false
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1
# use_peft: true
# lora_r: 64
# lora_alpha: 16